import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import rollupJson from "rollup-plugin-json";
import commonjs from "@rollup/plugin-commonjs";
import fs from "fs";
import path from "path";

const isProd = process.env.BUILD === "production";

const currentDir = path.dirname(__filename);

const copyPlugin = {
  name: "copy-plugin-assets",
  buildStart() {
    const buildDir = path.resolve(currentDir, "build");
    fs.mkdirSync(buildDir, { recursive: true });
    fs.copyFileSync(
      path.resolve(currentDir, "manifest.json"),
      path.join(buildDir, "manifest.json")
    );
    fs.copyFileSync(
      path.resolve(currentDir, "styles.css"),
      path.join(buildDir, "styles.css")
    );
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "src/main.ts",
  output: {
    dir: "./build",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  plugins: [
    copyPlugin,
    typescript(),
    nodeResolve({ browser: true }),
    rollupJson(),
    commonjs(),
  ],
  onwarn(warning, warn) {
    // workaround to prevent rollup build error
    if (
      warning.code === "EVAL" &&
      /.*\/node_modules\/file-type\/.*/.test(warning.loc.file)
    ) {
      return;
    }
    warn(warning);
  },
};
