import {copyFileSync, mkdirSync} from "node:fs";
import {dirname, resolve} from "node:path";
import commonjs from "@rollup/plugin-commonjs";
import {nodeResolve} from "@rollup/plugin-node-resolve";
import esbuild from "rollup-plugin-esbuild";

const root = dirname(import.meta.filename);
const production = process.env.BUILD === "production";

const copyAssets = {
  name: "copy-assets",
  buildStart() {
    const buildDir = resolve(root, "build");
    mkdirSync(buildDir, {recursive: true});
    for (const file of ["manifest.json", "styles.css"])
      copyFileSync(resolve(root, file), resolve(buildDir, file));
  },
};

export default {
  input: "src/main.ts",
  output: {
    dir: "build",
    format: "cjs",
    exports: "default",
    sourcemap: "inline",
    sourcemapExcludeSources: production,
    banner: "/* Generated by Rollup. See the plugin source for details. */",
  },
  external: ["obsidian", "node:path"],
  plugins: [
    copyAssets,
    nodeResolve({browser: true, preferBuiltins: false}),
    commonjs(),
    esbuild({tsconfig: resolve(root, "tsconfig.json"), minify: production}),
  ],
  onwarn(warning, warn) {
    if (warning.code === "EVAL" && warning.id?.includes("file-type")) return;
    warn(warning);
  },
};
