// Fills <vault>/Awesome Image Dev with notes and images so Awesome Image has
// something to work on. Images are downloaded from Wikimedia Commons when
// seeding runs, so the repository itself never carries binaries.
//
// Usage: npm run seed -- <vault-path>
//
// The vault path defaults to $OBSIDIAN_VAULT. The fixture folder is always
// overwritten; nothing outside it is touched.

import {mkdir, readdir, rm, stat, writeFile} from "node:fs/promises";
import path from "node:path";

const FIXTURE_FOLDER = "Awesome Image Dev";
const MARKER = ".awesome-image-seed.json";
const USER_AGENT = "obsidian-awesome-image-seed/1.0 (dev fixture script)";
const DOWNLOAD_TIMEOUT_MS = 20_000;
const DOWNLOAD_ATTEMPTS = 4;

// Permanent Wikimedia Commons URLs. Thumbnail widths are restricted to a fixed
// set, so stick to a size the imageinfo API hands out (960 here).
const REMOTE = {
  cat: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/960px-Cat03.jpg",
  gull: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Gull_portrait_ca_usa.jpg/960px-Gull_portrait_ca_usa.jpg",
  apple: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/960px-Red_Apple.jpg",
  earth: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/960px-The_Earth_seen_from_Apollo_17.jpg",
  dice: "https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png",
};

const IMAGES = [
  {file: "attachments/cat.jpg", url: REMOTE.cat},
  {file: "attachments/gull.jpg", url: REMOTE.gull},
  {file: "attachments/apple.jpg", url: REMOTE.apple},
  {file: "attachments/earth.jpg", url: REMOTE.earth},
  {file: "attachments/dice.png", url: REMOTE.dice},
  // Never mentioned by any note or canvas: these are the orphan candidates.
  {file: "Unreferenced/orphan-earth.jpg", url: REMOTE.earth},
  {file: "Unreferenced/orphan-dice.png", url: REMOTE.dice},
];

const vaultArgument = process.argv[2] || process.env.OBSIDIAN_VAULT;

if (!vaultArgument) {
  console.error("Usage: npm run seed -- <vault-path>");
  process.exit(1);
}

const vault = path.resolve(vaultArgument);
const target = path.join(vault, FIXTURE_FOLDER);

const vaultStats = await stat(vault).catch(() => null);
if (!vaultStats?.isDirectory()) {
  console.error(`Not a directory: ${vault}`);
  process.exit(1);
}

if (!(await stat(path.join(vault, ".obsidian")).catch(() => null))) {
  console.warn(`Warning: no .obsidian folder in ${vault} - is this a vault root?`);
}

const existing = await readdir(target).catch(() => []);
if (existing.length) {
  // Only ever wipe a folder this script built, never a real notes folder that
  // happens to share the name.
  if (!existing.includes(MARKER)) {
    console.error(
      `${target} is not an Awesome Image fixture folder. Move it away or delete it by hand first.`
    );
    process.exit(1);
  }
  await rm(target, {recursive: true, force: true});
}

// Canvas stores vault-absolute paths, so the fixture folder name has to be part
// of them. Notes use relative or bare-name links and stay location independent.
const vaultFolder = FIXTURE_FOLDER;

const NOTES = {
  "Readme.md": `# Awesome Image dev fixtures

Generated by \`npm run seed\`. Nothing here is precious: running the command again
overwrites the whole folder.

## What each note is for

| Note | Exercises |
| --- | --- |
| [Remote Images](Remote%20Images.md) | External \`![]()\` embeds. One URL is used twice, so processing should download it once and point both links at the same file. |
| [Local Markdown](Local%20Markdown.md) | Images that are already local. Processing should leave these alone. |
| [Wiki Embeds](Wiki%20Embeds.md) | \`![[...]]\` embeds. Target for converting wiki links to Markdown. |
| [Frontmatter Note](Frontmatter%20Note.md) | Image referenced from YAML frontmatter. |
| [Mixed Syntax](Mixed%20Syntax.md) | Wiki embed, Markdown embed and a remote embed in one note. |
| [Nested/Level Two](Nested/Level%20Two.md) | Remote image inside a nested folder. |
| [Nested/Level Three](Nested/Level%20Three/Level%20Three.md) | Wiki link resolved from a deeper folder. |
| [Canvas/Board](Canvas/Board.canvas) | Canvas file nodes pointing at images. Canvases are not processed as pages, but they do count as references. |

- \`attachments/\` - the local images the notes above point at.
- \`Unreferenced/\` - two images nothing points at. They should show up when you
  look for orphan images.

## Caveats worth remembering

- A frontmatter image only counts as a reference when Obsidian can parse it as a
  link, e.g. \`cover: "[[attachments/apple.jpg]]"\`. A bare path string such as
  \`cover: attachments/apple.jpg\` is plain text and is reported as unused.
- Manual test: paste a screenshot into a note with real-time update enabled to
  exercise the "Pasted image ..." renaming path.
`,

  "Remote Images.md": `# Remote Images

Every embed below points at Wikimedia Commons. Processing this note should
download each file into the media root, rename it by content hash, and rewrite
the link.

The first two embeds use the same URL on purpose. They should collapse into a
single local file with two identical links.

![](${REMOTE.cat})

![](${REMOTE.cat})

![](${REMOTE.gull})

A PNG, so the extension has to come from the file content:

![](${REMOTE.dice})
`,

  "Local Markdown.md": `# Local Markdown

Both images already live in the vault, so processing this note should change
nothing.

![](attachments/cat.jpg)

![Transparent die](attachments/dice.png)
`,

  "Wiki Embeds.md": `# Wiki Embeds

Run the wiki-to-Markdown conversion on this note; both embeds should become
\`![]()\` links.

![[gull.jpg]]

![[earth.jpg|400]]
`,

  "Frontmatter Note.md": `---
title: Frontmatter Note
cover: "[[attachments/apple.jpg]]"
---

# Frontmatter Note

The cover above is referenced from frontmatter only. It must not be reported as
an unused image.
`,

  "Mixed Syntax.md": `# Mixed Syntax

Wiki embed:

![[cat.jpg]]

Markdown embed:

![](attachments/dice.png)

Remote embed:

![](${REMOTE.apple})
`,

  "Nested/Level Two.md": `# Level Two

A remote image two levels below the vault root:

![](${REMOTE.earth})
`,

  "Nested/Level Three/Level Three.md": `# Level Three

A wiki link resolved from a deeper folder:

![[gull.jpg]]
`,

  "Canvas/Board.canvas": `${JSON.stringify(
    {
      nodes: [
        {
          id: "seed-image-earth",
          type: "file",
          file: `${vaultFolder}/attachments/earth.jpg`,
          x: -320,
          y: -160,
          width: 480,
          height: 360,
        },
        {
          id: "seed-image-cat",
          type: "file",
          file: `${vaultFolder}/attachments/cat.jpg`,
          x: 240,
          y: -160,
          width: 480,
          height: 360,
        },
        {
          id: "seed-note",
          type: "text",
          text: "Both images count as canvas references.",
          x: -120,
          y: 260,
          width: 400,
          height: 80,
        },
      ],
      edges: [],
    },
    null,
    2
  )}\n`,
};

async function write(relativePath, content, encoding) {
  const file = path.join(target, relativePath);
  await mkdir(path.dirname(file), {recursive: true});
  await writeFile(file, content, encoding);
}

for (const [relativePath, content] of Object.entries(NOTES)) {
  await write(relativePath, content, "utf8");
}

// One request per distinct URL, sequentially: Wikimedia rate limits bursts.
const cache = new Map();

async function fetchBytes(url) {
  const cached = cache.get(url);
  if (cached) return cached;

  let lastError;
  for (let attempt = 1; attempt <= DOWNLOAD_ATTEMPTS; attempt += 1) {
    try {
      const response = await fetch(url, {
        headers: {"User-Agent": USER_AGENT},
        signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS),
      });
      if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
      const bytes = Buffer.from(await response.arrayBuffer());
      cache.set(url, bytes);
      return bytes;
    } catch (error) {
      lastError = error;
      // Wikimedia throttles bursts, so back off generously between attempts.
      if (attempt < DOWNLOAD_ATTEMPTS) {
        await new Promise((resolve) => setTimeout(resolve, attempt * 3000));
      }
    }
  }
  throw lastError;
}

let failed = 0;
for (const image of IMAGES) {
  try {
    await write(image.file, await fetchBytes(image.url));
  } catch (error) {
    failed += 1;
    console.warn(`  ! ${image.file}: ${error.message}`);
  }
}

await write(
  MARKER,
  `${JSON.stringify(
    {
      generator: "obsidian-awesome-image/scripts/seed.mjs",
      createdAt: new Date().toISOString(),
      folder: FIXTURE_FOLDER,
    },
    null,
    2
  )}\n`,
  "utf8"
);

const written = Object.keys(NOTES).length + IMAGES.length - failed + 1;
console.log(`Seeded ${written} files in ${target}`);
console.log(`Images: ${IMAGES.length - failed} downloaded, ${failed} failed.`);
if (failed) process.exitCode = 1;
